include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_final_fields: true
