# Copyright 2022 The AnimatedSvg Author. All rights reserved.
# Use of this source code is governed by a MIT-style license that
# can be found in the LICENSE file.

name: animated_svg
description: Flutter package for displaying and animating Scalable Vector
  Graphics 1.1 files.
version: 1.0.0
homepage: https://github.com/BBarisKilic/Animated-SVG

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # An SVG rendering and widget library for Flutter.
  flutter_svg: ^1.0.3

dev_dependencies:
  # Recommended set of lints for good coding practices.
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter: null
