# Copyright 2022 The AnimatedSvg Author. All rights reserved.
# Use of this source code is governed by a MIT-style license that
# can be found in the LICENSE file.

name: media_player
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animated_svg:
    path: ../../
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
